version: 2
jobs:
  build:
    working_directory: ~/ng2learning
    docker:
      - image: circleci/node:6.10.3-browsers
    steps:
      - checkout
      - run:
          name: install-angular-cli
          command: 'sudo npm install -g @angular/cli'
      - run:
          name: npm install
          command: npm install --path devpro/
      - run:
          name: building angular app
          command: |
            cd devpro/
            ng build
 
  test:
    machine:true
    steps:
      - checkout
      - run:
          name: test
          command: |
            cd devpro/
            ng test
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
